.TH SUPERTUX2 6 "December 17, 2006" "SuperTux 0.3.2-SVN" "Games"
.SH NAME
supertux2 \- preview release of SuperTux Milestone 2, a classic style 2D platform game
.SH SYNOPSIS
.B supertux2
.RI [ options ]
.br
.B supertux2
.RI [ options ] " level.stl"
.br
.B supertux2
.RI [ options ] " worldmap.stwm"
.br
.SH DESCRIPTION
SuperTux is a classic style 2D platform game.
Run and jump through multiple worlds, fighting off enemies by jumping
on them, bumping them from below or tossing objects at them, grabbing
power-ups and other stuff on the way.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-f, \-\-fullscreen
Run in fullscreen mode
.TP
.B \-w, \-\-window
Run in window mode
.TP
.B \-g, \-\-geometry WIDTHxHEIGHT
Run SuperTux in given resolution (eg. \-g 800x600) 
.TP
.B \-a, \-\-aspect WIDTH:HEIGHT
Run SuperTux with given aspect ratio (eg. \-a 4:3) 
.TP
.B \-d, \-\-default
Reset video settings to default values (\-g 800x600 \-a auto \-w) 
.TP
.B \-\-renderer RENDERER
Render the game using the specified video renderer. Valid values are sdl, opengl, and auto (the default). 
.TP
.B \-\-disable\-sfx
Disable sound effects
.TP
.B \-\-disable\-music
Disable music
.TP
.B \-\-help
Show this help message
.TP
.B \-\-version
Display SuperTux version and quit
.TP
.B \-\-console
Enable ingame scripting console
.TP
.B \-\-noconsole
Disable ingame scripting console
.TP
.B \-\-show\-fps
Display framerate in levels
.TP
.B \-\-no\-show\-fps
Do not display framerate in levels
.TP
.B \-\-record\-demo FILE LEVEL
Record a demo to FILE
.TP
.B \-\-play\-demo FILE LEVEL
Play a recorded demo
.SH ENVIRONMENT
.TP
.B SUPERTUX_LANG
Overrides locale detection and forces locale to given value, e.g. "de_DE".
.SH FILES
.TP
.B ~/.supertux2
Contains configuration and savegames.
Also acts as an overlay of the SuperTux game data path: 
Files placed here, as well as contents of Zip archives in this directory, 
will override or supplement game data files.
.SH EXAMPLES
To play level /tmp/mylevel.stl in a window of size 800x600, run 
the program like this:
.IP
.B supertux2 --window --geometry 800x600 /tmp/mylevel.stl
.LP
To play a previously recorded demo /tmp/mylevel.demo of level 
/tmp/mylevel.stl, run SuperTux like this: 
.IP
.B supertux2 --play-demo /tmp/mylevel.demo /tmp/mylevel.stl
.LP
.PP
Custom-made levels can be conveniently stored in the overlay data folder. 
.PP
.TP
.B ~/.supertux2/levels/sample_collection/level01.stl
.nf
(supertux-level
  (version 2)
  (name (_ "Sample Level"))
  (author "Myself")
  ...
.fi
.PP
Make sure to also create an "info" file, so the collection will be 
recognized by SuperTux.
.TP
.B ~/.supertux2/levels/sample_collection/info
.nf
;SuperTux-Level-Subset
(supertux-level-subset
  (title "Sample Collection")
  (description "")
)
.fi
.PP
For easier distribution, the level collection can be bundled in a Zip
archive.
.PP
.TP
.B ~/.supertux2/sample_collection.zip
.nf
levels/sample_collection/info
levels/sample_collection/level01.stl
 ...
.fi
.SH BUGS
This is a development version, so expect plenty of bugs.
.SH AUTHOR
This manual page was written by the SuperTux Devel Team 
and is placed in the public domain.
