/**
 * WARNING: This file is automatically generated from './build/i686-pc-linux-gnu/optimize/miniswig.tmp' - do not change
 */
#ifndef __supertux_WRAPPER_H__
#define __supertux_WRAPPER_H__

#include "wrapper_util.h"

extern WrappedFunction supertux_global_functions[];
extern WrappedClass supertux_classes[];

#endif

