find_package(OggVorbis REQUIRED)

add_library(OggVorbis INTERFACE)
set_target_properties(OggVorbis PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${VORBIS_INCLUDE_DIR}"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${VORBIS_INCLUDE_DIR}"
  INTERFACE_LINK_LIBRARIES "${OGGVORBIS_LIBRARIES}"
  )

mark_as_advanced(
  OGG_LIBRARY
  VORBISENC_LIBRARY
  VORBISFILE_LIBRARY
  VORBIS_INCLUDE_DIR
  VORBIS_LIBRARY
  )

# EOF #
