add_subdirectory("${CMAKE_SOURCE_DIR}/external/simplesquirrel/")
if(MSVC)
  add_library(LibSimpleSquirrel ALIAS simplesquirrel_static)
else()
  add_library(LibSimpleSquirrel ALIAS simplesquirrel)
endif()
