if(EMSCRIPTEN)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -sUSE_VORBIS=1")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -sUSE_VORBIS=1")
  set(CMAKE_LINKER_FLAGS "${CMAKE_LINKER_FLAGS} -sUSE_VORBIS=1")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -sUSE_VORBIS=1")
else()
  find_package(OggVorbis REQUIRED)

  add_library(LibOggVorbis INTERFACE IMPORTED)
  set_target_properties(LibOggVorbis PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${VORBIS_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES "${OGGVORBIS_LIBRARIES}"
    )

  mark_as_advanced(
    OGG_LIBRARY
    VORBISENC_LIBRARY
    VORBISFILE_LIBRARY
    VORBIS_INCLUDE_DIR
    VORBIS_LIBRARY
    )
endif()
# EOF #
