Import('*')

libsupertux_src = Glob(
    dirs=[
        "app",
        "audio",
        "gui",
        "math",
        "special",
        "utils",
        "video"
    ],
    pattern="*.cpp"
)
lib = env.Library(
    target="supertux",
    source=libsupertux_src
)
Default(lib)

