Import('*')

libsupertux_src = Glob("app/*.cpp") \
                + Glob("audio/*.cpp") \
                + Glob("gui/*.cpp") \
                + Glob("math/*.cpp") \
                + Glob("special/*.cpp") \
                + Glob("utils/*.cpp") \
                + Glob("video/*.cpp") \
                + Glob("lisp/*.cpp")

lib = env.Library(
    target="supertux",
    source=libsupertux_src
)
Default(lib)

