//          Copyright Timothy Goya 2007.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)

GL_PROC(void, glClearColor, (GLclampf, GLclampf, GLclampf, GLclampf))
GL_PROC(void, glClear, (GLbitfield))
GL_PROC(void, glBlendFunc, (GLenum, GLenum))
GL_PROC(void, glDrawBuffer, (GLenum))
GL_PROC(void, glReadBuffer, (GLenum))
GL_PROC(void, glEnable, (GLenum))
GL_PROC(void, glDisable, (GLenum))
GL_PROC(void, glGetIntegerv, (GLenum, GLint *))
GL_PROC(GLenum, glGetError, (void))
GL_PROC(const GLubyte *, glGetString, (GLenum))
GL_PROC(void, glMatrixMode, (GLenum))
GL_PROC(void, glOrtho, (GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble))
GL_PROC(void, glViewport, (GLint, GLint, GLsizei, GLsizei))
GL_PROC(void, glPushMatrix, (void))
GL_PROC(void, glPopMatrix, (void))
GL_PROC(void, glLoadIdentity, (void))
GL_PROC(void, glRotatef, (GLfloat, GLfloat, GLfloat))
GL_PROC(void, glScalef, (GLfloat, GLfloat, GLfloat))
GL_PROC(void, glTranslatef, (GLfloat, GLfloat, GLfloat))
GL_PROC(void, glBegin, (GLenum))
GL_PROC(void, glEnd, (void))
GL_PROC(void, glVertex2i, (GLint, GLint))
GL_PROC(void, glColor4ub, (GLubyte, GLubyte, GLubyte, GLubyte))
GL_PROC(void, glReadPixels, (GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *))
GL_PROC(void, glTexCoord2f, (GLfloat, GLfloat))
GL_PROC(void, glPixelStorei, (GLenum, GLint))
GL_PROC(void, glTexParameteri, (GLenum, GLenum, GLint))
GL_PROC(void, glTexImage2D, (GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *))
GL_PROC(void, glTexSubImage2D, (GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *))
GL_PROC(void, glGetTexImage, (GLenum, GLint, GLenum, GLenum, GLvoid *))
GL_PROC(void, glGenTextures, (GLsizei, GLuint *))
GL_PROC(void, glDeleteTextures, (GLsizei, GLuint *))
GL_PROC(void, glBindTexture, (GLsizei, GLuint))
