#!/usr/bin/env python
#
# SuperTux
# Copyright (C) 2014 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function


import argparse
import glob
import hashlib
import os
import shutil
import subprocess
import sys

import sexpr


def escape_str(str):
    return "\"%s\"" % str.replace("\"", "\\\"")


class Addon(object):
    def __init__(self, id, version, type, title, author, license, md5="", url=""):
        self.id = id
        self.version = int(version)
        self.type = type
        self.title = title
        self.author = author
        self.license = license
        self.md5 = md5
        self.url = url

    @classmethod
    def from_nfo(self, filename):
        lst = sexpr.parse(filename)
        if lst[0][0] != "supertux-addoninfo":
            raise Exception("not a supertux-addoninfo: %s" % lst[0][0])
        else:
            tags = {}
            for k, v in lst[0][1:]:
                if k == "id":
                    id = v
                elif k == "version":
                    version = int(v)
                elif k == "type":
                    type = v
                elif k == "title":
                    title = v
                elif k == "author":
                    author = v
                elif k == "license":
                    license = v
                else:
                    raise Exception("unknown tag: %s" % k)

            md5 = ""
            url = ""

            return self(id, version, type, title, author, license, md5, url)

    def write(self, fout, is_package=False):
        fout.write("  (supertux-addoninfo\n")
        fout.write("    (id %s)\n" % escape_str(self.id))
        fout.write("    (version %d)\n" % self.version)
        fout.write("    (type %s)\n" % escape_str(self.type))
        fout.write("    (title %s)\n" % escape_str(self.title))
        fout.write("    (author %s)\n" % escape_str(self.author))
        fout.write("    (license %s)\n" % escape_str(self.license))
        if not is_package:
            fout.write("    (url %s)\n" % escape_str(self.url))
            fout.write("    (md5 %s)\n" % escape_str(self.md5))
        fout.write("   )\n")


def process_addon(fout, addon_dir, nfo, base_url, zipdir):
    # print addon_dir, nfo
    with open(nfo) as fin:
        addon = Addon.from_nfo(fin.read())

    zipfile = addon.id + "_v" + str(addon.version) + ".zip"

    # see http://pivotallabs.com/barriers-deterministic-reproducible-zip-files/
    if os.path.exists(os.path.join(zipdir, zipfile)):
        os.remove(os.path.join(zipdir, zipfile))
    zipout = os.path.relpath(os.path.join(zipdir, zipfile), addon_dir)
    subprocess.call(["zip", "-X", "-r", "--quiet", zipout, "."], cwd=addon_dir)

    with open(os.path.join(zipdir, zipfile), 'rb') as fin:
        addon.md5 = hashlib.md5(fin.read()).hexdigest()

    addon.url = base_url + zipfile

    addon.write(fout)

def process_langpack(fout, langpack_dir, base_url, zipdir):
    addon = Addon(os.path.basename(langpack_dir),
                  1,
                  "languagepack",
                  os.path.basename(langpack_dir).split('-', 1)[-1],
                  "Various Translators",
                  "GPL 2+ / CC-by-sa 3.0")

    nfofile = addon.id + ".nfo"
    with open(os.path.join(langpack_dir, nfofile), 'w') as nfoout:
        addon.write(nfoout, is_package=True)

    zipfile = addon.id + ".zip"

    if os.path.exists(os.path.join(zipdir, zipfile)):
        os.remove(os.path.join(zipdir, zipfile))
    zipout = os.path.relpath(os.path.join(zipdir, zipfile), langpack_dir)
    subprocess.call(["zip", "-X", "-r", "--quiet", zipout, "."], cwd=langpack_dir)

    with open(os.path.join(zipdir, zipfile), 'rb') as fin:
        addon.md5 = hashlib.md5(fin.read()).hexdigest()

    addon.url = base_url + zipfile

    addon.write(fout)

def generate_index(fout, directory, base_url, zipdir, translations, langdir):
    fout.write(";; automatically generated by build-addon-index.py\n")
    fout.write("(supertux-addons\n")
    for addon_dir in os.listdir(directory):
        addon_dir = os.path.join(directory, addon_dir)
        if os.path.isdir(addon_dir):
            print(addon_dir)
            nfos = glob.glob(os.path.join(addon_dir, "*.nfo"))
            if len(nfos) == 0:
                raise Exception(".nfo file missing from %s" % addon_dir)
            elif len(nfos) > 1:
                raise Exception("to many .nfo files in %s" % addon_dir)
            else:
                try:
                    process_addon(fout, addon_dir, nfos[0], base_url, zipdir)
                except Exception as e:
                    sys.stderr.write("%s: ignoring addon because: %s\n" % (addon_dir, e))
    for resource in os.listdir(translations):
        resource_dir = os.path.join(translations, resource)
        if os.path.isdir(resource_dir):
            print(resource_dir)
            pos = glob.glob(os.path.join(resource_dir, "*.po"))
            for po in pos:
                language = os.path.splitext(os.path.basename(po))[0]
                language_dir = os.path.join(langdir,
                               "langpack-{language}".format(language=language),
                               "langpack-{language}".format(language=language))
                lresource_dir = os.path.join(language_dir, resource)
                if not os.path.isdir(language_dir):
                    os.makedirs(language_dir)
                if not os.path.isdir(lresource_dir):
                    os.makedirs(lresource_dir)
                shutil.copy2(po, lresource_dir)
    for langpack_dir in os.listdir(langdir):
        langpack_dir = os.path.join(langdir, langpack_dir)
        if os.path.isdir(langpack_dir):
            print(langpack_dir)
            try:
                process_langpack(fout, langpack_dir, base_url, zipdir)
            except Exception as e:
                sys.stderr.write("%s: ignoring langpack because: %s\n" % (langpack_dir, e))
    fout.write(")\n\n;; EOF ;;\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Addon Index/Zip Generator')
    parser.add_argument('DIRECTORY', type=str, nargs=1,
                        help="directory containing the mods")
    parser.add_argument('TRANSLATIONS', type=str, nargs=1,
                        help="directory containing the translations")
    parser.add_argument('-o', '--output', metavar='FILE', type=str, required=False,
                        help="output file")
    parser.add_argument('-z', '--zipdir', metavar="DIR", type=str, required=True,
                        help="generate zip files")
    parser.add_argument('-l', '--langdir', metavar="DIR", type=str, required=True,
                        help="generate language files")
    parser.add_argument('-u', '--url', metavar='FILE', type=str,
                        default="https://raw.githubusercontent.com/SuperTux/addons/master/repository/",
                        help="base url")
    args = parser.parse_args()

    if args.output is None:
        fout = sys.stdout
        generate_index(fout, args.DIRECTORY[0], args.url, args.zipdir,
            args.TRANSLATIONS[0], args.langdir)
    else:
        with open(args.output, "w") as fout:
            generate_index(fout, args.DIRECTORY[0], args.url, args.zipdir,
                args.TRANSLATIONS[0], args.langdir)

# EOF #
