Import('*')

supertux_src = Glob(
    dirs=[".", "object", "badguy", "trigger"],
    pattern="*.cpp"
)
app = env.Program(
    target="supertux",
    source = supertux_src
)
AddPostAction(app, "ln -sf $TARGET .")
Default(app)

