#  SuperTux
#  Copyright (C) 2025 Hyland B. <me@ow.swag.toys>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Flatpak
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    env:
      APPID: "org.supertux.SuperTuxNightly"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch the whole tree so git describe works
          fetch-depth: 0
          submodules: recursive

      - name: Generate flatpak release/debug inputs
        run: |
          sh mk/flatpak/gen_flatpaks.sh
          ls -la mk/flatpak/gen_flatpaks.sh

        # TODO: I generate the outputs for the releases still in the source
        # dir. Switching to mk/flatpak is easy for teh output files, but i'm too
        # lazy.

      - name: Nightly build
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: SuperTuxNightly.flatpak
          manifest-path: org.supertux.SuperTuxNightly.yml
          cache-key: flatpak-builder-nightly-${{ github.sha }}

      - name: Release build
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: SuperTux.flatpak
          manifest-path: org.supertux.SuperTux.yml
          cache-key: flatpak-builder-release-${{ github.sha }}

      - name: Create Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: 'build/upload/SuperTux*'
          draft: true
