#  SuperTux
#  Copyright (C) 2022 HybridDog
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Code Linting

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  CPPCHECK_VERSION: '2.22.0'

jobs:
  lint_cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # The apt version of Cppcheck is outdated and apparently there are no
      # alternative up-to-date precompiled versions for Ubuntu,
      # so we compile it ourselves here.
      - name: Install Cppcheck
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make
          TARBALL_URL="$(gh api "repos/cppcheck-opensource/cppcheck/releases/tags/$CPPCHECK_VERSION" --jq .tarball_url)"
          test -n "$TARBALL_URL" && test "$TARBALL_URL" != null
          curl --fail --show-error --location --retry 3 --output cppcheck.tar.gz "$TARBALL_URL"
          mkdir cppcheck
          tar --extract --gzip --file=cppcheck.tar.gz --strip-components=1 --directory=cppcheck
          make -C cppcheck -j"$(nproc)" CXXFLAGS="-O1 -DNDEBUG"
          ./cppcheck/cppcheck --version

      - name: Lint code with Cppcheck
        run: |
          ./cppcheck/cppcheck \
            --check-level=exhaustive --include=mk/cppcheck/include/SDL.h \
            --quiet --inline-suppr --language=c++ --error-exitcode=10 \
            -j"$(nproc)" --std=c++17 --enable=warning,style \
            --suppress=useStlAlgorithm -U__EMSCRIPTEN__ -UDOXYGEN_SCRIPTING src/
