name: WebAssembly
'on':
  workflow_dispatch: null
  push:
    tags:
    - '*'
  schedule:
  - cron: 10 5 * * 2
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}
permissions:
  contents: read
defaults:
  run:
    shell: bash
env:
  EMSDK_VERSION: 6.0.11
  VCPKG_COMMIT: c748cb44f2a435fcf015c35225c9d5545fe0021c
  VCPKG_MAX_CONCURRENCY: '4'
jobs:
  wasm:
    strategy:
      fail-fast: false
      matrix:
        build_type:
        - Release
        - Debug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: ./.github/actions/build-web
      with:
        build_type: ${{ matrix.build_type }}
