if(ANDROID_ABI STREQUAL "arm64-v8a")
  set(VCPKG_TARGET_TRIPLET "arm64-android")
elseif(ANDROID_ABI STREQUAL "armeabi-v7a")
  set(VCPKG_TARGET_TRIPLET "arm-neon-android")
elseif(ANDROID_ABI STREQUAL "x86_64")
  set(VCPKG_TARGET_TRIPLET "x64-android")
elseif(ANDROID_ABI STREQUAL "x86")
  set(VCPKG_TARGET_TRIPLET "x86-android")
else()
  message(FATAL_ERROR "Invalid Android ABI: ${ANDROID_ABI}")
endif()

include($ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)
